# Local Variables:
# mode: makefile
# indent-tabs-mode: nil
# End:
# vim: set ft=make :

alias show-secret := view-secret

provision tags='':
    #!/usr/bin/env bash
    username=$(grep username hosts.yml | tr -d ' ' | cut -d ':' -f2)
    username=${username//\"/}

    if [ -z {{tags}} ]; then
        ANSIBLE_VAULT_PASSWORD_FILE=scripts/vault_password.sh \
            ansible-playbook -i hosts.yml -u $username -K --become-method=su site.yml -e provision_hosts=all
    else
        ANSIBLE_VAULT_PASSWORD_FILE=scripts/vault_password.sh \
            ansible-playbook -i hosts.yml -u $username -K --become-method=su site.yml -e provision_hosts=all \
                -t {{tags}}
    fi

list-tags:
    ansible-playbook --list-tags site.yml

# create an ansible inventory (hosts.yml) for local provisioning
setup-local:
    #!/usr/bin/env bash
    cat <<EOF > hosts.yml
    ---
    # Autogenerated by: \`just setup-local\`
    all:
      vars:
        username: $USER
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: auto_silent
    EOF

# copy the SSH key, and create an ansible inventory (hosts.yml)
setup-box username ip port='22':
    #!/usr/bin/env bash
    ssh-copy-id -p {{port}} {{username}}@{{ip}} &> /dev/null
    cat <<EOF > hosts.yml
    ---
    # Autogenerated by: \`just setup-box {{username}} {{ip}} {{port}}\`
    all:
      vars:
        username: {{username}}
      hosts:
        the_machine:
          ansible_host: {{ip}}
          ansible_port: {{port}}
          ansible_python_interpreter: auto_silent
    EOF

# for debugging
remove-user-from-wheel-group:
    #!/usr/bin/env bash
    username=$(grep username hosts.yml | tr -d ' ' | cut -d ':' -f2)
    username=${username//\"/}

    ansible -i hosts.yml -u $username the_machine -K \
            -a "gpasswd -d $username wheel" --become --become-method su

decrypt filename:
    ANSIBLE_VAULT_PASSWORD_FILE=scripts/vault_password.sh ansible-vault decrypt {{filename}}

encrypt filename:
    ANSIBLE_VAULT_PASSWORD_FILE=scripts/vault_password.sh ansible-vault encrypt {{filename}}

create-secret filename:
    ANSIBLE_VAULT_PASSWORD_FILE=scripts/vault_password.sh ansible-vault create {{filename}}

view-secret filename:
    ANSIBLE_VAULT_PASSWORD_FILE=scripts/vault_password.sh ansible-vault view {{filename}}

edit-secret filename:
    ANSIBLE_VAULT_PASSWORD_FILE=scripts/vault_password.sh ansible-vault edit {{filename}}
