---
- name: get dotfiles and stow them
  block:
    - git:
        repo: git@github.com:joncol/dotfiles.git
        dest: ~/dotfiles

    - file:
        path: ~/.aws
        state: directory

    - file:
        path: ~/.cabal
        state: directory

    - file:
        path: ~/.config
        state: directory

    - file:
        path: ~/.config/Slack
        state: directory

    - file:
        path: ~/.config/emacs
        state: directory

    - file:
        path: ~/.config/nix
        state: directory

    - file:
        path: ~/.config/tmux
        state: directory

    - file:
        path: ~/.local/bin
        state: directory

    - file:
        path: ~/.local/share/applications
        state: directory

    - file:
        path: ~/.xmonad
        state: directory

    - command:
        chdir: ~/dotfiles
        cmd: stow -t ~ homedir

  tags: [dotfiles]
