---
- name: get dotfiles and stow them
  block:
    - git:
        repo: https://github.com/joncol/dotfiles.git
        dest: ~/dotfiles
        force: yes

    - file:
        path: ~/.aws
        state: directory

    - file:
        path: ~/.config
        state: directory

    - file:
        path: ~/.config/Slack
        state: directory

    - file:
        path: ~/.config/tmux
        state: directory

    - file:
        path: ~/.xmonad
        state: directory

    - command:
        chdir: ~/dotfiles
        cmd: stow -t ~ homedir

  tags: [dotfiles]
