---
- block:
    - package:
        name:
          - dunst
          - feh
          - gnome-keyring
          - maim
          - redshift
          - screenkey
          - scrot
          - unclutter
          - xclip
          - xsel
          - xterm
      become: yes

    - package:
        name:
          - arc-gtk-theme
          - faba-icon-theme
          - gvfs
          - libnotify
          - libsecret
          - slock
          - xf86-input-wacom
          - xorg-server
          - xorg-xdpyinfo
          - xorg-xinput
          - xorg-xmessage
          - xorg-xrdb
      when: ansible_distribution == 'Archlinux'
      become: yes

    - package:
        name:
          - libnotify-bin
          - libsecret-1-0
          - libwacom-bin
          - libx11-dev
          - libxinerama-dev
          - libxft-dev
          - picom
          - suckless-tools
          - x11-xserver-utils
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      become: yes

    - systemd:
        name: lightdm
        enabled: yes
      become: yes

    - copy:
        src: x-init-kb.sh
        dest: ~/.local/bin/
        mode: preserve

    - name: build dmenu2 from source
      block:
        - file:
            path: ~/repos/dmenu2
            state: directory

        - hg:
            repo: https://bitbucket.org/melek/dmenu2
            dest: ~/repos/dmenu2

        - make:
            chdir: ~/repos/dmenu2
            target: "{{ item }}"
          loop:
            - clean
            - install

      become: yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - aur:
        name:
          - dmenu2
          - picom-tryone-git
      when: ansible_distribution == 'Archlinux'

  tags: x
