- name: install zshell
  package:
    name: zsh,fzf
  become: yes

- name: change default shell of current user
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
  become: yes

- package: {name: zsh-antigen}
  become: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- kewlfft.aur.aur: {name: antigen}
  when: ansible_distribution == 'Archlinux'
