---
- package:
    name:
      - autoconf
      - binutils
      - curl
      - fakeroot
      - git
      - htop
      - hub
      - mercurial
      - ncdu
      - python-pip
      - ripgrep
      - stow
      - texinfo
      - tig
      - tree

- shell: timedatectl set-timezone Europe/Stockholm

- name: enable locale
  block:
    - lineinfile:
        path: /etc/locale.gen
        regexp: '#en_US.UTF-8 UTF-8'
        line: 'en_US.UTF-8 UTF-8'
    - shell: locale-gen
  when: ansible_distribution == 'Archlinux'

- name: Arch Linux specific packages and setup
  block:
    - package:
        name:
          - base-devel
          - bat
          - man-db
          - man-pages
          - fd
          - openssh
          - pkgfile
          - the_silver_searcher
          - wget

    - aur: name=direnv
      become: no

    - name: update pkgfile database
      command: pkgfile --update

  when: ansible_distribution == 'Archlinux'

- name: Debian/Ubuntu specific packages and setup
  package:
    name:
      - build-essential
      - direnv
      - fd-find
      - silversearcher-ag
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- systemd:
    name: sshd.service
    enabled: yes
    state: started

  when: ansible_distribution == 'Archlinux'
