---
- package:
    name:
      - at
      - autoconf
      - binutils
      - curl
      - cmake
      - discount
      - exa
      - fakeroot
      - git
      - htop
      - hub
      - irssi
      - lastpass-cli
      - lsof
      - mercurial
      - ncdu
      - postgresql
      - python-pip
      - ripgrep
      - rsync
      - sdcv
      - stow
      - texinfo
      - tig
      - tree
      - unzip
      - zip

- shell: timedatectl set-timezone Europe/Stockholm

- name: enable locale
  block:
    - lineinfile:
        path: /etc/locale.gen
        regexp: '#en_US.UTF-8 UTF-8'
        line: 'en_US.UTF-8 UTF-8'
    - shell: locale-gen
  when: ansible_distribution == 'Archlinux'

- name: Arch Linux specific packages and setup
  block:
    - package:
        name:
          - base-devel
          - bat
          - bind
          - hunspell-en_US
          - inetutils
          - man-db
          - man-pages
          - fd
          - openssh
          - pkgfile
          - postgresql-libs
          - the_silver_searcher
          - wget

    - kewlfft.aur.aur:
        name:
          - aws-cli-v2-bin
      become: no

    - name: update pkgfile database
      command: pkgfile --update

  when: ansible_distribution == 'Archlinux'

- name: Debian/Ubuntu specific packages and setup
  block:
    - package:
        name:
          - build-essential
          - direnv
          - dnsutils
          - fd-find
          - hostname
          - hunspell-en-us
          - postgresql-client
          - silversearcher-ag

    - apt:
        deb: https://github.com/mozilla/sops/releases/download/v3.6.0/sops_3.6.0_amd64.deb

    - pip: name=awscli
      become: no

  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- systemd:
    name: sshd.service
    enabled: yes
    state: started

  when: ansible_distribution == 'Archlinux'
