---
- package:
    name:
      - autoconf
      - binutils
      - curl
      - fakeroot
      - git
      - htop
      - hub
      - jq
      - lastpass-cli
      - mercurial
      - ncdu
      - postgresql
      - python-pip
      - ripgrep
      - stow
      - texinfo
      - tig
      - tree
      - unzip

- shell: timedatectl set-timezone Europe/Stockholm

- name: enable locale
  block:
    - lineinfile:
        path: /etc/locale.gen
        regexp: '#en_US.UTF-8 UTF-8'
        line: 'en_US.UTF-8 UTF-8'
    - shell: locale-gen
  when: ansible_distribution == 'Archlinux'

- name: Arch Linux specific packages and setup
  block:
    - package:
        name:
          - aws-cli
          - base-devel
          - bat
          - inetutils
          - man-db
          - man-pages
          - fd
          - openssh
          - pkgfile
          - postgresql-lib
          - the_silver_searcher
          - wget

    - aur:
        name:
          - direnv
          - git-delta
      become: no

    - name: update pkgfile database
      command: pkgfile --update

  when: ansible_distribution == 'Archlinux'

- name: Debian/Ubuntu specific packages and setup
  block:
    - package:
        name:
          - build-essential
          - direnv
          - fd-find
          - hostname
          - postgresql-client
          - silversearcher-ag

    - apt:
        deb: https://github.com/dandavison/delta/releases/download/0.3.0/git-delta_0.3.0_amd64.deb

    - pip: name=awscli
      become: no

  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- systemd:
    name: sshd.service
    enabled: yes
    state: started

  when: ansible_distribution == 'Archlinux'
