---
- package:
    name:
      - binutils
      - fakeroot
      - hub
      - mercurial
      - stow

- shell: timedatectl set-timezone Europe/Stockholm

- name: locale setup
  block:
    - lineinfile:
        path: /etc/locale.gen
        regexp: '#en_US.UTF-8 UTF-8'
        line: 'en_US.UTF-8 UTF-8'
    - shell: locale-gen
  when: ansible_distribution == 'Archlinux'

- apt: {name: build-essential}
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: install Arch Linux specific packages
  package:
    name:
      - base-devel
      - man-db
      - man-pages
      - openssh
      - wget
  when: ansible_distribution == 'Archlinux'

- name: install pkgfile
  block:
    - pacman: {name: pkgfile}
    - command: {cmd: pkgfile --update}
  when: ansible_distribution == 'Archlinux'

- package: {name: direnv}
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- aur: {name: direnv}
  become: no
  when: ansible_distribution == 'Archlinux'

- systemd:
    name: sshd.service
    enabled: yes
    state: started

  when: ansible_distribution == 'Archlinux'
