---
- aur: name=emacs-git
  when: ansible_distribution == 'Archlinux'
  tags: emacs

- name: build and install emacs on Debian/Ubuntu
  block:
    - package:
        name:
          - libgif-dev
          - libgnutls28-dev
          - libgtk-3-dev
          - libjpeg-dev
          - libtiff-dev
          - libxpm-dev

    - git:
        repo: https://github.com/emacs-mirror/emacs.git
        dest: ~/repos/emacs

    - command:
        chdir: ~/repos/emacs
        cmd: ./autogen.sh

    - command:
        chdir: ~/repos/emacs
        cmd: ./configure

    - make:
        chdir: ~/repos/emacs
        params:
          NUM_THREADS: 4

    - make:
        chdir: ~/repos/emacs
        target: install

  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  become: yes
  tags: emacs, x

- pip: name=certifi
