- name: create `wheel` group
  group:
    name: wheel
    state: present
- name: install sudo package
  package:
    name: sudo
    state: present
- name: allow `wheel` group to have passwordless sudo
  lineinfile:
    path: /etc/sudoers
    regexp: '^# %wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    # validate: "visudo -cf %s"
- name: add user to groups
  user:
    name: "{{ ansible_user_id }}"
    groups:
      - video
      - wheel
    append: yes
    state: present
