---
- name: install neovim
  block:
    - package: name=neovim
      become: yes

    - file:
        path: ~/.local/share/nvim/site/autoload
        state: directory

    - get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: ~/.local/share/nvim/site/autoload/

    - shell: nvim -es -u ~/.config/nvim/init.vim -i NONE -c "PlugInstall" -c "qa"

  tags: neovim

- pip: name=pynvim
  when: ansible_distribution == 'Archlinux'
