---
- name: update pacman cache
  pacman: update_cache=yes
  changed_when: False
  when: ansible_distribution == 'Archlinux'

- name: update apt cache
  apt: update_cache=yes
  changed_when: False
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
