---
- block:
    - package:
        name:
          - noto-fonts-emoji
          - ttf-fira-code
          - ttf-liberation
      become: yes
      when: ansible_distribution == 'Archlinux'

    - kewlfft.aur.aur:
        name:
          - montserrat-font-ttf
          - ttf-iosevka
          - ttf-ms-fonts
          - ttf-windows
      when: ansible_distribution == 'Archlinux'

    - package: {name: fonts-firacode}
      become: yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  tags: [x, fonts]
